-- ============================================================
-- GulfMart Retail Inventory Analytics
-- 02_create_tables.sql
-- ============================================================
-- Star-schema tables. Natural keys (the VARCHAR IDs already
-- generated by the Python pipeline) are used as primary keys
-- throughout -- they are stable, unique, and deterministic, so
-- surrogate IDENTITY keys would add ETL complexity without a
-- corresponding benefit here.
--
-- fact_sales uses a staging + transform pattern: the raw CSV has
-- 35 columns, many of them demand-modeling intermediates needed
-- only during generation (base_demand, seasonality_factor,
-- demand_intensity, etc.). staging_fact_sales mirrors the CSV
-- exactly for a clean BULK INSERT target; fact_sales is the final,
-- normalized table with only true fact-grain measures and keys,
-- populated from staging via 03_load_data.sql.
--
-- fact_inventory has no staging table: it is loaded via a Python
-- script (not BULK INSERT, see README), which selects and types
-- its columns in pandas before insert, so this DDL already defines
-- its final, normalized structure directly.
-- ============================================================

USE GulfMartRetailAnalytics;
GO



-- ============================================================
-- Drop existing tables (idempotent re-run during development)
-- Order matters: tables with foreign keys must drop before the
-- tables they reference.
-- ============================================================

IF OBJECT_ID('dbo.fact_inventory', 'U') IS NOT NULL DROP TABLE dbo.fact_inventory;
IF OBJECT_ID('dbo.fact_sales', 'U') IS NOT NULL DROP TABLE dbo.fact_sales;
IF OBJECT_ID('dbo.staging_fact_sales', 'U') IS NOT NULL DROP TABLE dbo.staging_fact_sales;
IF OBJECT_ID('dbo.staging_dim_date', 'U') IS NOT NULL DROP TABLE dbo.staging_dim_date;
IF OBJECT_ID('dbo.dim_customer', 'U') IS NOT NULL DROP TABLE dbo.dim_customer;
IF OBJECT_ID('dbo.dim_product', 'U') IS NOT NULL DROP TABLE dbo.dim_product;
IF OBJECT_ID('dbo.dim_store', 'U') IS NOT NULL DROP TABLE dbo.dim_store;
IF OBJECT_ID('dbo.dim_supplier', 'U') IS NOT NULL DROP TABLE dbo.dim_supplier;
IF OBJECT_ID('dbo.dim_date', 'U') IS NOT NULL DROP TABLE dbo.dim_date;
GO

-- ============================================================
-- STAGING TABLE — dim_date (mirrors raw CSV; boolean columns as
-- VARCHAR since BULK INSERT cannot convert text "True"/"False"
-- directly into BIT)
-- ============================================================

CREATE TABLE dbo.staging_dim_date (
    [date]        DATE        NOT NULL,
    [year]        SMALLINT    NOT NULL,
    quarter       CHAR(2)     NOT NULL,
    [month]       TINYINT     NOT NULL,
    month_name    VARCHAR(10) NOT NULL,
    week_of_year  TINYINT     NOT NULL,
    [day]         TINYINT     NOT NULL,
    day_name      VARCHAR(10) NOT NULL,
    day_of_week   TINYINT     NOT NULL,
    is_weekend    VARCHAR(5)  NOT NULL,   -- 'True'/'False' text, converted on load
    season        VARCHAR(10) NOT NULL,
    is_ramadan    VARCHAR(5)  NOT NULL,
    is_eid_period VARCHAR(5)  NOT NULL
);
GO

-- ============================================================
-- DIMENSION TABLES
-- ============================================================

CREATE TABLE dbo.dim_date (
    [date]        DATE        NOT NULL PRIMARY KEY,
    [year]        SMALLINT    NOT NULL,
    quarter       CHAR(2)     NOT NULL,
    [month]       TINYINT     NOT NULL,
    month_name    VARCHAR(10) NOT NULL,
    week_of_year  TINYINT     NOT NULL,
    [day]         TINYINT     NOT NULL,
    day_name      VARCHAR(10) NOT NULL,
    day_of_week   TINYINT     NOT NULL,
    is_weekend    BIT         NOT NULL,
    season        VARCHAR(10) NOT NULL,
    is_ramadan    BIT         NOT NULL,
    is_eid_period BIT         NOT NULL
);
GO

CREATE TABLE dbo.dim_supplier (
    supplier_id       VARCHAR(10) NOT NULL PRIMARY KEY,
    supplier_name     VARCHAR(50) NULL,   -- nullable: may be an imputed placeholder from 02_data_cleaning.ipynb
    supplier_region   VARCHAR(20) NOT NULL,
    lead_time_days    SMALLINT    NOT NULL,
    minimum_order_qty INT         NOT NULL,
    supplier_status   VARCHAR(20) NOT NULL
);
GO

CREATE TABLE dbo.dim_product (
    product_id          VARCHAR(10)   NOT NULL PRIMARY KEY,
    product_name        VARCHAR(100)  NOT NULL,
    category             VARCHAR(30)   NOT NULL,
    subcategory          VARCHAR(30)   NOT NULL,
    brand                 VARCHAR(30)   NULL,   -- nullable: may be missing (not imputed -- dim_product had no planted issue requiring it)
    supplier_id           VARCHAR(10)   NOT NULL,
    unit_cost              DECIMAL(10,2) NOT NULL,
    selling_price           DECIMAL(10,2) NOT NULL,
    product_status           VARCHAR(20)   NOT NULL,
    product_launch_date       DATE          NOT NULL,
    shelf_life_days            SMALLINT      NOT NULL,
    demand_class                VARCHAR(20)   NOT NULL,
    demand_trajectory            VARCHAR(20)   NOT NULL,
    base_demand                   DECIMAL(10,4) NOT NULL,
    CONSTRAINT FK_dim_product_supplier FOREIGN KEY (supplier_id)
        REFERENCES dbo.dim_supplier (supplier_id)
);
GO

CREATE TABLE dbo.dim_store (
    store_id            VARCHAR(10)  NOT NULL PRIMARY KEY,
    store_name          VARCHAR(50)  NOT NULL,
    city                 VARCHAR(30)  NOT NULL,
    region                VARCHAR(20)  NOT NULL,
    store_type             VARCHAR(20)  NOT NULL,
    opening_date             DATE         NOT NULL,
    store_size_sqm            INT          NOT NULL,
    channel                    VARCHAR(20)  NOT NULL,
    store_demand_factor         DECIMAL(6,2) NOT NULL
);
GO

CREATE TABLE dbo.dim_customer (
    customer_id                VARCHAR(10)  NOT NULL PRIMARY KEY,
    customer_segment            VARCHAR(20)  NOT NULL,
    gender                        VARCHAR(10)  NOT NULL,
    age_group                      VARCHAR(10)  NOT NULL,
    city                             VARCHAR(30)  NULL,  -- nullable: may be an imputed placeholder
    customer_start_date                DATE         NOT NULL,
    customer_tenure_days                 INT          NOT NULL,
    preferred_channel                      VARCHAR(20)  NOT NULL,
    purchase_frequency_factor                DECIMAL(6,2) NOT NULL,
    average_basket_factor                      DECIMAL(6,2) NOT NULL,
    price_sensitivity                            DECIMAL(4,2) NOT NULL
);
GO

-- ============================================================
-- STAGING TABLE — fact_sales (mirrors the raw CSV exactly)
-- ============================================================

CREATE TABLE dbo.staging_fact_sales (
    transaction_id            VARCHAR(12)   NOT NULL,
    transaction_date           DATE          NOT NULL,
    product_id                   VARCHAR(10)   NOT NULL,
    store_id                       VARCHAR(10)   NOT NULL,
    customer_id                      VARCHAR(10)   NOT NULL,
    base_demand                        DECIMAL(10,4) NOT NULL,
    demand_class                         VARCHAR(20)   NOT NULL,
    demand_class_factor                    DECIMAL(6,2)  NOT NULL,
    demand_trajectory                        VARCHAR(20)   NOT NULL,
    demand_trajectory_factor                   DECIMAL(6,2)  NOT NULL,
    category                                     VARCHAR(30)   NOT NULL,
    unit_cost                                      DECIMAL(10,2) NOT NULL,
    product_selling_price                            DECIMAL(10,2) NOT NULL,
    store_demand_factor                                DECIMAL(6,2)  NOT NULL,
    customer_frequency_factor                            DECIMAL(6,2)  NOT NULL,
    customer_basket_factor                                 DECIMAL(6,2)  NOT NULL,
    price_sensitivity                                        DECIMAL(4,2)  NOT NULL,
    [month]                                                    TINYINT       NOT NULL,
    day_of_week                                                  TINYINT       NOT NULL,
    season                                                         VARCHAR(10)   NOT NULL,
    day_of_week_factor                                               DECIMAL(6,2)  NOT NULL,
    is_ramadan        VARCHAR(5)  NOT NULL,
    is_eid_period     VARCHAR(5)  NOT NULL,
    seasonality_factor                                                     DECIMAL(6,2)  NOT NULL,
    demand_intensity                                                         DECIMAL(10,2) NOT NULL,
    demand_spike      VARCHAR(5)  NOT NULL,
    is_promotion      VARCHAR(5)  NOT NULL,
    discount_pct                                                                   DECIMAL(5,4)  NOT NULL,
    quantity                                                                         INT           NOT NULL,
    unit_price                                                                         DECIMAL(10,2) NOT NULL,
    gross_sales                                                                          DECIMAL(12,2) NOT NULL,
    discount_amount                      DECIMAL(12,2) NOT NULL,
    net_sales                       DECIMAL(12,2) NOT NULL,
    cogs                           DECIMAL(12,2) NOT NULL,
    gross_profit                  DECIMAL(12,2) NOT NULL
);
GO

-- ============================================================
-- FINAL FACT TABLE — fact_sales (normalized: keys + measures only)
-- Populated from staging_fact_sales in 03_load_data.sql.
-- Demand-modeling intermediates (base_demand, seasonality_factor,
-- demand_intensity, etc.) are dropped here -- they were needed to
-- GENERATE the data, not to analyze it, and are redundant with
-- attributes already stored once in dim_product/dim_store.
-- ============================================================

CREATE TABLE dbo.fact_sales (
    transaction_id    VARCHAR(12)   NOT NULL PRIMARY KEY,
    transaction_date  DATE          NOT NULL,
    product_id        VARCHAR(10)   NOT NULL,
    store_id          VARCHAR(10)   NOT NULL,
    customer_id       VARCHAR(10)   NOT NULL,
    quantity          INT           NOT NULL,
    unit_price        DECIMAL(10,2) NOT NULL,
    discount_pct      DECIMAL(5,4)  NOT NULL,
    gross_sales       DECIMAL(12,2) NOT NULL,
    discount_amount   DECIMAL(12,2) NOT NULL,
    net_sales         DECIMAL(12,2) NOT NULL,
    cogs              DECIMAL(12,2) NOT NULL,
    gross_profit      DECIMAL(12,2) NOT NULL,
    is_promotion      BIT           NOT NULL,
    demand_spike      BIT           NOT NULL,
    CONSTRAINT FK_fact_sales_date FOREIGN KEY (transaction_date)
        REFERENCES dbo.dim_date ([date]),
    CONSTRAINT FK_fact_sales_product FOREIGN KEY (product_id)
        REFERENCES dbo.dim_product (product_id),
    CONSTRAINT FK_fact_sales_store FOREIGN KEY (store_id)
        REFERENCES dbo.dim_store (store_id),
    CONSTRAINT FK_fact_sales_customer FOREIGN KEY (customer_id)
        REFERENCES dbo.dim_customer (customer_id)
);
GO

CREATE NONCLUSTERED INDEX IX_fact_sales_product ON dbo.fact_sales (product_id);
CREATE NONCLUSTERED INDEX IX_fact_sales_store ON dbo.fact_sales (store_id);
CREATE NONCLUSTERED INDEX IX_fact_sales_date ON dbo.fact_sales (transaction_date);
GO

-- ============================================================
-- FINAL FACT TABLE — fact_inventory
-- Populated via a Python loader (pyodbc/sqlalchemy), not BULK
-- INSERT -- see 03_load_data notes in the README. Column set is
-- the analytically meaningful subset of the ~46-column pandas
-- table: true inventory-flow components, computed policy fields,
-- and event flags. Static-per-combo fields (lead_time_days,
-- minimum_order_qty, safety_stock_days, replenishment_interval_days)
-- are intentionally retained here despite being available via
-- dim_supplier/dim_product joins in principle -- doing so avoids
-- forcing every downstream inventory-policy query in 05-08 to
-- join through dim_supplier just to reach a value that changes
-- only 30 times across the whole catalog, and matches how the
-- Python analysis notebooks already carry these fields directly
-- on fact_inventory rows.
-- ============================================================

CREATE TABLE dbo.fact_inventory (
    [date]                     DATE          NOT NULL,
    store_id                    VARCHAR(10)   NOT NULL,
    product_id                    VARCHAR(10)   NOT NULL,
    supplier_id                     VARCHAR(10)   NOT NULL,
    opening_stock                     INT           NOT NULL,
    closing_stock                       INT           NOT NULL,
    sales_units                           INT           NOT NULL,
    receipts                                INT           NOT NULL,
    transfers_in                              INT           NOT NULL,
    transfers_out                               INT           NOT NULL,
    returns_units                                 INT           NOT NULL,
    damaged_units                                   INT           NOT NULL,
    inventory_adjustments                             INT           NOT NULL,
    demand_rate                                         DECIMAL(10,4) NOT NULL,
    safety_stock_units                                    DECIMAL(10,2) NOT NULL,
    lead_time_days                                          SMALLINT      NOT NULL,
    minimum_order_qty                                         INT           NOT NULL,
    replenishment_interval_days                                 SMALLINT      NOT NULL,
    reorder_point                                                 DECIMAL(10,2) NOT NULL,
    target_stock_level                                              DECIMAL(10,2) NOT NULL,
    planned_order_quantity                                            INT           NOT NULL,
    inventory_status                                                    VARCHAR(20)   NOT NULL,
    stockout_event                                                        BIT           NOT NULL,
    low_stock_event                                                         BIT           NOT NULL,
    inventory_coverage_days                                                   DECIMAL(12,4) NULL,  -- nullable: undefined (NaN) when demand_rate = 0
    CONSTRAINT PK_fact_inventory PRIMARY KEY ([date], store_id, product_id),
    CONSTRAINT FK_fact_inventory_date FOREIGN KEY ([date])
        REFERENCES dbo.dim_date ([date]),
    CONSTRAINT FK_fact_inventory_product FOREIGN KEY (product_id)
        REFERENCES dbo.dim_product (product_id),
    CONSTRAINT FK_fact_inventory_store FOREIGN KEY (store_id)
        REFERENCES dbo.dim_store (store_id),
    CONSTRAINT FK_fact_inventory_supplier FOREIGN KEY (supplier_id)
        REFERENCES dbo.dim_supplier (supplier_id)
);
GO

CREATE NONCLUSTERED INDEX IX_fact_inventory_product ON dbo.fact_inventory (product_id);
CREATE NONCLUSTERED INDEX IX_fact_inventory_store ON dbo.fact_inventory (store_id);
CREATE NONCLUSTERED INDEX IX_fact_inventory_status ON dbo.fact_inventory (inventory_status);
GO

PRINT 'All tables created successfully.';
GO